// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "debug": boolean;
      "inference.provider": string;
      "ollama.url": string;
      "ollama.model": string;
      "openai.key": string;
      "openai.model": string;
      "limits.maxExecutionTime": number;
      "limits.maxInferenceCalls": number;
      "limits.maxNetworkRequests": number;
      "limits.maxStorageBytes": number;
      "autoUpdateAgents": boolean;
    };
  }
}
